
source 'https://github.com/ZhouPeter/Spec.git'
use_frameworks!

platform :ios, '13.0'

target 'XGLib_Example' do
  pod 'XGLib', :path => '../'
  
  target 'XGLib_Tests' do
    inherit! :search_paths

    
  end
end
